id: P004357
initial_creation_type: ocr
source_metadata:
  id: bdr:W21595
  title: དྲི་མེད་ཀུན་ལྡན་གྱི་མཛད་རྣམ
  author: ''
  volumes:
    087f2cb297c84f308c12ee4f4de6de1a:
      image_group_id: I4709
      title: ''
      volume_number: 1
      total_pages: 86
