id: P004357
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:14:32.717688
source_metadata:
  id: bdr:W21595
  title: དྲི་མེད་ཀུན་ལྡན་གྱི་མཛད་རྣམ
  author: ''
  volumes:
    087f2cb297c84f308c12ee4f4de6de1a:
      image_group_id: I4709
      title: ''
      volume_number: 1
      total_pages: 86
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
