id: IBB099922
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T04:40:45+00:00'
last_modified: '2022-06-07T22:15:58.823646+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21595
  title: དྲི་མེད་ཀུན་ལྡན་གྱི་མཛད་རྣམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9607':
      image_group_id: I4709
      title: ''
      total_pages: 86
      order: 1
      base_file: 9607.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
